docker run -it -d \
  --label traefik.http.routers.kalumbulugroup.rule=Host\(\`kalumbulugroup.org\`\) \
  --label traefik.http.routers.kalumbulugroup.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.kalumbulugroup.tls=true \
  --label traefik.http.routers.kalumbulugroup.service=kalumbulugroup-credit-http \
  --label traefik.http.services.kalumbulugroup-credit-http.loadbalancer.server.port=80 \
  --name kalumbulugroup \
  --network web \
  --restart always \
  --expose 80 \
ubuntu:latest





# docker run -it -d \
#   --label traefik.http.routers.minecomicrofinance.rule=Host\(\`minecomicrofinance.online\`\) \
#   --label traefik.http.routers.minecomicrofinance.tls.certresolver=lets-encrypt \
#   --label traefik.http.routers.minecomicrofinance.tls=true \
#   --label traefik.http.routers.minecomicrofinance.service=minecomicrofinance-credit-http \
#   --label traefik.http.services.minecomicrofinance-credit-http.loadbalancer.server.port=80 \
#   --name minecomicrofinance \
#   --network web \
#   --restart always \
#   --expose 80 \
# mikoposoft/nackcredit:12dec2025