docker run -it -d \
  --label traefik.http.routers.kalumbulugroup.rule=Host\(\`kalumbulugroup.org\`\) \
  --label traefik.http.routers.kalumbulugroup.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.kalumbulugroup.tls=true \
  --label traefik.http.routers.kalumbulugroup.service=kalumbulugroup-credit-http \
  --label traefik.http.services.kalumbulugroup-credit-http.loadbalancer.server.port=80 \
  --name kalumbulugroup \
  --network web \
  --restart always \
  --expose 80 \
ubuntu:latest