<?php

namespace App\Http\Controllers;

use App\Models\Member;
use App\Models\Collection;
use App\Models\Payment;
use App\Models\PenaltyForgiveness;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Barryvdh\DomPDF\Facade\Pdf as PDF;
use Mpdf\Mpdf;
use Carbon\Carbon;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     */
public function index(Request $request)
{
    $search = $request->get('search');
    $payType = $request->get('pay_type', $request->route('pay_type'));
    $paidTodayFilter = $request->get('paid_today');
    $perPage = (int) $request->get('per_page', 10);
    if (!in_array($perPage, [10, 50, 100], true)) {
        $perPage = 10;
    }

    if ($payType && !in_array($payType, ['mchango_mdogo', 'mchango_mkubwa'], true)) {
        $payType = null;
    }

    $today = Carbon::today();

    $members = Member::query()
        ->with([
            'collections',
            'payments' => function ($q) use ($today) {
                $q->whereDate('payment_date', $today)
                  ->where('payment_type', 'regular');
            }
        ])

        // ✅ Filter: Paid Today Only
        ->when($paidTodayFilter, function ($query) use ($today) {
            $query->whereHas('payments', function ($q) use ($today) {
                $q->whereDate('payment_date', $today)
                  ->where('payment_type', 'regular');
            });
        })

        ->when($search, function ($query, $search) {
            return $query->where(function ($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('phone', 'like', "%{$search}%")
                  ->orWhere('address', 'like', "%{$search}%")
                  ->orWhere('business_address', 'like', "%{$search}%");
            });
        })

        ->when($payType, function ($query, $payType) {
            return $query->where('pay_type', $payType);
        })

        ->orderBy('created_at', 'desc')
        ->paginate($perPage)
        ->withQueryString(); // ✅ keep filters when paginating

    // ✅ Dashboard Stats
    $totalPaidToday = Payment::whereDate('payment_date', $today)
        ->where('payment_type', 'regular')
        ->sum('amount');

    $countPaidMembersToday = Payment::whereDate('payment_date', $today)
        ->where('payment_type', 'regular')
        ->distinct('member_id')
        ->count('member_id');

    return view('member.index', compact(
        'members',
        'payType',
        'totalPaidToday',
        'countPaidMembersToday'
    ));
}




public function downloadPdf(Request $request)
{
    $search  = $request->get('search');
    $payType = $request->get('pay_type');

    $members = Member::with('collections')
        ->when($search, function ($query, $search) {
            $query->where(function ($q) use ($search) {
                $q->where('name', 'like', "%{$search}%")
                  ->orWhere('phone', 'like', "%{$search}%")
                  ->orWhere('address', 'like', "%{$search}%")
                  ->orWhere('business_address', 'like', "%{$search}%");
            });
        })
        ->when($payType, function ($query, $payType) {
            $query->where('pay_type', $payType);
        })
        ->orderBy('created_at', 'desc')
        ->get();

    $data = compact('members', 'payType', 'search');

    $mpdf = new Mpdf([
        'mode'   => 'utf-8',
        'format' => 'A4-L'
    ]);

    $html = view('member.pdf', $data)->render();

    $mpdf->WriteHTML($html);
    $mpdf->SetFooter('Generated By James Mwakalinga');

    return response()->streamDownload(function () use ($mpdf) {
        $mpdf->Output();
    }, 'members.pdf');
}



    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
  public function store(Request $request)
{
    $validatedData = $request->validate([
        'name' => 'required|string|max:255',
        'phone' => 'required|string|max:20',
        'address' => 'nullable|string|max:255',
        'business_address' => 'nullable|string|max:255',
        'type' => 'required|in:daily,weekly,monthly',
        'start_date' => 'required|date',
        'pay_type' => 'required|in:mchango_mdogo,mchango_mkubwa',
        'number_type' => 'required|numeric|min:1',
        'penalty_per_day' => 'nullable|numeric|min:0',
    ]);

    /* ===============================
       SET AMOUNT BASED ON PAY TYPE
    ================================*/
    if ($validatedData['pay_type'] === 'mchango_mdogo') {
        $validatedData['amount'] = 5000;
        // Set default penalty if not provided (100% of daily amount)
        if (!isset($validatedData['penalty_per_day']) || $validatedData['penalty_per_day'] == 0) {
            $validatedData['penalty_per_day'] = 2000; // 100% of 5000
        }
    } elseif ($validatedData['pay_type'] === 'mchango_mkubwa') {
        $validatedData['amount'] = 10000;
        // Set default penalty if not provided (100% of daily amount)
        if (!isset($validatedData['penalty_per_day']) || $validatedData['penalty_per_day'] == 0) {
            $validatedData['penalty_per_day'] = 3000; // 100% of 10000
        }
    }

    // Add 255 prefix to phone
    $phone = $validatedData['phone'];
    if (!str_starts_with($phone, '255')) {
        $phone = ltrim($phone, '0');
        $validatedData['phone'] = '255' . $phone;
    }

    // Calculate end_date: start_date + number_type days
   if (isset($validatedData['start_date']) && isset($validatedData['number_type'])) {
    $startDate = Carbon::parse($validatedData['start_date']);
    $validatedData['end_date'] = $startDate->copy()
        ->addDays((int)$validatedData['number_type'] - 1)
        ->format('Y-m-d');
}


    DB::transaction(function () use ($validatedData) {

        // Create member
        $member = Member::create($validatedData);

        // Total amount = amount * number_type
        $totalAmount = $member->amount * $member->number_type;

        Collection::create([
            'member_id' => $member->id,
            'total_amount' => $totalAmount,
            'amount_paid' => 0,
            'balance' => $totalAmount,
            'total_penalty' => 0,
            'penalty_paid' => 0,
            'penalty_balance' => 0,
            'last_payment_date' => now(),
            'status' => 'pending',
        ]);
    });

    $message = "Karibu {$validatedData['name']} kwenye Kalumbulu Group Kikundi cha kuwezeshana. Karibu tushirikiane na kuwezeshana!";
    $this->sendsms($validatedData['phone'], $message);

    return $this->redirectToMembersBySession()
        ->with('success', 'Member created successfully.');
}

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
  public function update(Request $request, string $id)
{
    $validatedData = $request->validate([
        'name' => 'required|string|max:255',
        'phone' => 'required|string|max:20',
        'address' => 'nullable|string|max:255',
        'business_address' => 'nullable|string|max:255',
        'pay_type' => 'required|in:mchango_mdogo,mchango_mkubwa', // new field
        'type' => 'required|in:daily,weekly,monthly',
        'number_type' => 'required|numeric|min:1',
    ]);

    // Add 255 prefix to phone if not already present
    $phone = $validatedData['phone'];
    if (!str_starts_with($phone, '255')) {
        $phone = ltrim($phone, '0');
        $validatedData['phone'] = '255' . $phone;
    }

    // Automatic amount based on pay_type
    if ($validatedData['pay_type'] === 'mchango_mdogo') {
        $validatedData['amount'] = 5000;
        // Keep existing penalty or set default (100% of daily amount)
        $member = Member::findOrFail($id);
        if ($member->penalty_per_day == 0) {
            $validatedData['penalty_per_day'] = 5000;
        }
    } elseif ($validatedData['pay_type'] === 'mchango_mkubwa') {
        $validatedData['amount'] = 10000;
        // Keep existing penalty or set default (100% of daily amount)
        $member = Member::findOrFail($id);
        if ($member->penalty_per_day == 0) {
            $validatedData['penalty_per_day'] = 10000;
        }
    }

    $member = Member::findOrFail($id);

    // Calculate end_date if start_date exists and number_type is provided
    if ($member->start_date && isset($validatedData['number_type'])) {
        $startDate = Carbon::parse($member->start_date);
        $validatedData['end_date'] = $startDate->copy()->addDays((int)$validatedData['number_type'])->format('Y-m-d');
    }

    DB::transaction(function () use ($member, $validatedData) {
        $member->update($validatedData);
        $member->refresh();

        $collection = $member->collections()->first();
        if ($collection) {
            $newTotalAmount = $member->amount * $member->number_type;
            $collection->total_amount = $newTotalAmount;
            $collection->balance = max($newTotalAmount - $collection->amount_paid, 0);
            $collection->save();
        }
    });

    return $this->redirectToMembersBySession()->with('success', 'Member updated successfully.');
}


    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        // Only admin can delete members
        if (!auth()->user()->isAdmin()) {
            return $this->redirectToMembersBySession()
                ->with('error', 'Hairuhusiwi kufuta wanachama. Harufu za admin kwa kufanya hatua hii.');
        }

        $member = Member::findOrFail($id);
        $member->delete();
        
        return $this->redirectToMembersBySession()->with('success', 'Member deleted successfully.');
    }

    /**
     * Forgive penalty for a member
     */
    public function forgivePenalty(string $id)
    {
        $member = Member::findOrFail($id);
        $collection = $member->collections()->first();
        
        if ($collection && $collection->penalty_balance > 0) {
            DB::transaction(function () use ($collection) {
                // Reset all penalty values to zero
                $collection->total_penalty = 0;
                $collection->penalty_paid = 0;
                $collection->penalty_balance = 0;
                // Update last payment date to today to prevent immediate re-accumulation
                $collection->last_payment_date = now();
                $collection->save();
            });
            
            return $this->redirectToMembersBySession()->with('success', 'Faini imesamehewa kikamilifu.');
        }
        
        return $this->redirectToMembersBySession()->with('info', 'Hakuna faini ya kusamehe.');
    }

    public function bulkForgivePenalty(Request $request)
    {
        if (!auth()->user()->isAdmin()) {
            return $this->redirectToMembersBySession()
                ->with('error', 'Hairuhusiwi kusamehe faini kwa wingi.');
        }

        $validated = $request->validate([
            'member_ids' => ['required', 'array', 'min:1'],
            'member_ids.*' => ['integer', 'exists:members,id'],
        ]);

        /** @var \Illuminate\Database\Eloquent\Collection<int, \App\Models\Member> $members */
        $members = Member::query()->with('collections')
            ->whereIn('id', $validated['member_ids'])
            ->get();

        $forgivenCount = 0;

        DB::transaction(function () use ($members, &$forgivenCount) {
            /** @var \App\Models\Member $member */
            foreach ($members as $member) {
                $updated = Collection::where('member_id', $member->id)
                    ->where('penalty_balance', '>', 0)
                    ->update([
                        'total_penalty' => 0,
                        'penalty_paid' => 0,
                        'penalty_balance' => 0,
                        'last_payment_date' => now(),
                    ]);

                if ($updated > 0) {
                    $forgivenCount++;
                }
            }
        });

        if ($forgivenCount === 0) {
            return $this->redirectToMembersBySession()
                ->with('info', 'Hakuna faini ya kusamehe kwa waliochaguliwa.');
        }

        return $this->redirectToMembersBySession()
            ->with('success', "Faini zimesamehewa kwa wanachama {$forgivenCount}.");
    }

    public function bulkForgivePenaltyByDate(Request $request)
    {
        if (!auth()->user()->isAdmin()) {
            return $this->redirectToMembersBySession()
                ->with('error', 'Hairuhusiwi kusamehe faini kwa tarehe.');
        }

        $validated = $request->validate([
            'member_ids' => ['required', 'array', 'min:1'],
            'member_ids.*' => ['integer', 'exists:members,id'],
            'forgive_date' => ['required', 'date'],
        ]);

        $forgiveDate = Carbon::parse($validated['forgive_date'])->toDateString();

        $isClosedDate = DB::table('closed_accounts')
            ->whereDate('date', $forgiveDate)
            ->exists();

        if (!$isClosedDate) {
            return $this->redirectToMembersBySession()
                ->with('error', 'Tarehe uliyochagua haipo kwenye Funga Hesabu.');
        }

        $members = Member::query()->whereIn('id', $validated['member_ids'])->get();
        $forgivenCount = 0;

        DB::transaction(function () use ($members, $forgiveDate, &$forgivenCount) {
            foreach ($members as $member) {
                $hasAnyPayment = Payment::where('member_id', $member->id)
                    ->whereDate('payment_date', $forgiveDate)
                    ->exists();

                if ($hasAnyPayment) {
                    continue;
                }

                $alreadyForgiven = PenaltyForgiveness::where('member_id', $member->id)
                    ->whereDate('forgiven_date', $forgiveDate)
                    ->exists();

                if ($alreadyForgiven) {
                    continue;
                }

                $penaltyAmount = max((float) ($member->penalty_per_day ?? 0), 0);
                if ($penaltyAmount <= 0) {
                    continue;
                }

                $collection = Collection::where('member_id', $member->id)->first();
                if (!$collection) {
                    continue;
                }

                $currentTotal = (float) $collection->total_penalty;
                $currentPaid = (float) $collection->penalty_paid;

                $newTotal = max($currentTotal - $penaltyAmount, 0);
                $newPaid = min($currentPaid, $newTotal);
                $newBalance = max($newTotal - $newPaid, 0);

                Collection::where('id', $collection->id)->update([
                    'total_penalty' => $newTotal,
                    'penalty_paid' => $newPaid,
                    'penalty_balance' => $newBalance,
                    'last_payment_date' => now()->toDateString(),
                    'status' => ($collection->balance <= 0 && $newBalance <= 0)
                        ? 'completed'
                        : (($collection->amount_paid > 0 || $newPaid > 0) ? 'partial' : 'pending'),
                ]);

                PenaltyForgiveness::create([
                    'member_id' => $member->id,
                    'user_id' => auth()->id(),
                    'forgiven_date' => $forgiveDate,
                    'amount' => $penaltyAmount,
                    'notes' => 'Bulk forgiveness by date',
                ]);

                $forgivenCount++;
            }
        });

        if ($forgivenCount === 0) {
            return $this->redirectToMembersBySession()
                ->with('info', 'Hakuna faini iliyosamehewa kwa tarehe hiyo kwa waliochaguliwa.');
        }

        return $this->redirectToMembersBySession()
            ->with('success', "Faini zimesamehewa kwa wanachama {$forgivenCount} tarehe {$forgiveDate}.");
    }

    private function redirectToMembersBySession()
    {
        $payType = session('pay_type');

        if ($payType === 'mchango_mdogo') {
            return redirect()->route('members.index.mdogo');
        }

        if ($payType === 'mchango_mkubwa') {
            return redirect()->route('members.index.mkubwa');
        }

        return redirect()->route('members.index');
    }


     public function sendsms($phone,$massage){
    //public function sendsms(){f
    //$phone = '255628323760';
    //$massage = 'mapenzi yanauwa';
    // $api_key = '';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    //$api_key = 'qFzd89PXu1e/DuwbwxOE5uUBn6';
    //$curl = curl_init();
    $url = "https://sms-api.kadolab.com/api/send-sms";
    $token = getenv('SMS_TOKEN');

  
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
      'Authorization: Bearer '. $token,
      'Content-Type: application/json',
    ]);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode([
      "phoneNumbers" => ["+$phone"],
      "message" => $massage
    ]));
  
  $server_output = curl_exec($ch);
  curl_close ($ch);
  
  //print_r($server_output);
  }
  
}
